import { DashboardData, Interaction, Lead, Task } from "./types";

export const mockLeads: Lead[] = [
  {
    id: "lead-1",
    nome: "Ana Clara Mendes",
    cpfCnpj: "12345678900",
    whatsapp: "5565999991111",
    email: "ana@example.com",
    instagram: "@anacantora",
    cidade: "Cuiabá",
    estado: "MT",
    origem: "Instagram Orgânico",
    campanha: "Aula Aberta Voz Autoral",
    produtoInteresse: "Diagnóstico ALIANÇA",
    dorPrincipal: "Falta de direção artística",
    momentoArtistico: "Sou artista autoral",
    etapaFunil: "Diagnóstico Agendado",
    statusComercial: "Em atendimento",
    temperatura: "Muito quente",
    score: 92,
    responsavel: "Nath",
    proximaAcao: "Confirmar presença",
    dataProximaAcao: "2026-06-12T14:00:00.000Z",
    ultimaInteracao: "2026-06-10T18:00:00.000Z",
    consentimentoContato: true,
    statusFinanceiro: "Sem informação",
    valorPago: 0,
    valorVencido: 0,
    valorAVencer: 0,
  },
  {
    id: "lead-2",
    nome: "Bruno Vieira",
    whatsapp: "5565988882222",
    email: "bruno@example.com",
    instagram: "@brunomusica",
    cidade: "São Paulo",
    estado: "SP",
    origem: "Meta Lead Ads",
    campanha: "Diagnóstico Junho",
    produtoInteresse: "Estrada do Artista",
    dorPrincipal: "Repertório confuso",
    momentoArtistico: "Já me apresento",
    etapaFunil: "Proposta Enviada",
    statusComercial: "Proposta aberta",
    temperatura: "Quente",
    score: 78,
    responsavel: "Comercial",
    proximaAcao: "Follow-up de proposta",
    dataProximaAcao: "2026-06-13T12:00:00.000Z",
    ultimaInteracao: "2026-06-09T18:00:00.000Z",
    consentimentoContato: true,
    statusFinanceiro: "A vencer",
    valorPago: 0,
    valorVencido: 0,
    valorAVencer: 297,
  },
  {
    id: "lead-3",
    nome: "Carla Tavares",
    whatsapp: "5565977773333",
    email: "carla@example.com",
    cidade: "Goiânia",
    estado: "GO",
    origem: "Lista Antiga",
    produtoInteresse: "Premium / Tempo de Mesa",
    dorPrincipal: "Quer reposicionamento",
    momentoArtistico: "Quero reposicionar minha carreira",
    etapaFunil: "Reativação",
    statusComercial: "Cliente anterior",
    temperatura: "Quente",
    score: 84,
    responsavel: "Nath",
    proximaAcao: "Reativação com convite personalizado",
    dataProximaAcao: "2026-06-14T15:00:00.000Z",
    ultimaInteracao: "2026-05-25T18:00:00.000Z",
    consentimentoContato: true,
    statusFinanceiro: "Cliente/Comprador anterior",
    valorPago: 1200,
    valorVencido: 0,
    valorAVencer: 0,
  },
  {
    id: "lead-4",
    nome: "Diego Ramos",
    email: "diego@example.com",
    instagram: "@diegocompoe",
    cidade: "Rio de Janeiro",
    estado: "RJ",
    origem: "YouTube",
    produtoInteresse: "Direção Vocal/Artística para Projeto",
    dorPrincipal: "Quer lançar projeto",
    momentoArtistico: "Estou lançando projeto",
    etapaFunil: "Novo Lead",
    statusComercial: "Novo Lead",
    temperatura: "Morno",
    score: 45,
    responsavel: "Comercial",
    proximaAcao: "Enviar e-mail de nutrição",
    dataProximaAcao: "2026-06-12T10:00:00.000Z",
    consentimentoContato: false,
    statusFinanceiro: "Sem informação",
    valorPago: 0,
    valorVencido: 0,
    valorAVencer: 0,
  },
  {
    id: "lead-5",
    nome: "Ester Lima",
    whatsapp: "5565966664444",
    cidade: "Cuiabá",
    estado: "MT",
    origem: "Indicação",
    produtoInteresse: "Estrada do Artista",
    dorPrincipal: "Insegurança vocal",
    momentoArtistico: "Já estudo canto",
    etapaFunil: "Venda Realizada",
    statusComercial: "Cliente Ativo",
    temperatura: "Muito quente",
    score: 100,
    responsavel: "Nath",
    proximaAcao: "Acompanhar onboarding",
    ultimaInteracao: "2026-06-08T18:00:00.000Z",
    consentimentoContato: true,
    statusFinanceiro: "Cliente/Comprador anterior",
    valorPago: 297,
    valorVencido: 0,
    valorAVencer: 297,
  },
];

export const mockTasks: Task[] = [
  { id: "task-1", leadId: "lead-1", leadNome: "Ana Clara Mendes", titulo: "Confirmar diagnóstico", tipo: "Confirmação", status: "Pendente", dataVencimento: "2026-06-12T14:00:00.000Z", responsavel: "Nath" },
  { id: "task-2", leadId: "lead-2", leadNome: "Bruno Vieira", titulo: "Follow-up de proposta", tipo: "Follow-up", status: "Pendente", dataVencimento: "2026-06-13T12:00:00.000Z", responsavel: "Comercial" },
  { id: "task-3", leadId: "lead-3", leadNome: "Carla Tavares", titulo: "Convite de reativação", tipo: "Reativação", status: "Atrasada", dataVencimento: "2026-06-09T12:00:00.000Z", responsavel: "Nath" },
];

export const mockInteractions: Interaction[] = [
  { id: "int-1", leadId: "lead-1", tipo: "WhatsApp", descricao: "Lead pediu diagnóstico para clarear direção artística.", resultado: "Agendado", criadoEm: "2026-06-10T18:00:00.000Z" },
  { id: "int-2", leadId: "lead-2", tipo: "Proposta", descricao: "Proposta da comunidade enviada.", resultado: "Aguardando retorno", criadoEm: "2026-06-09T18:00:00.000Z" },
  { id: "int-3", leadId: "lead-3", tipo: "Sistema", descricao: "Importado da lista antiga como reativação.", resultado: "Processado", criadoEm: "2026-06-01T18:00:00.000Z" },
];

export const mockDashboard: DashboardData = {
  metrics: [
    { label: "Total de leads", value: "5", hint: "+2 esta semana" },
    { label: "Leads com WhatsApp", value: "4", hint: "80% da base" },
    { label: "Diagnósticos agendados", value: "1", hint: "Próximo em 24h" },
    { label: "Vendas realizadas", value: "1", hint: "20% dos leads" },
    { label: "Receita paga", value: "R$ 1.497", hint: "Ticket médio R$ 748,50" },
    { label: "Receita a vencer", value: "R$ 594", hint: "2 cobranças previstas" },
    { label: "CAC", value: "Dados insuficientes", hint: "Inclua investimento por campanha" },
    { label: "Churn", value: "Dados insuficientes", hint: "Sem cancelamentos no período" },
  ],
  funnel: [
    { etapa: "Novo Lead", total: 1 },
    { etapa: "Diagnóstico Agendado", total: 1 },
    { etapa: "Proposta Enviada", total: 1 },
    { etapa: "Venda Realizada", total: 1 },
    { etapa: "Reativação", total: 1 },
  ],
  origins: [
    { origem: "Instagram Orgânico", total: 1 },
    { origem: "Meta Lead Ads", total: 1 },
    { origem: "Lista Antiga", total: 1 },
    { origem: "YouTube", total: 1 },
    { origem: "Indicação", total: 1 },
  ],
  temperatures: [
    { temperatura: "Frio", total: 0 },
    { temperatura: "Morno", total: 1 },
    { temperatura: "Quente", total: 2 },
    { temperatura: "Muito quente", total: 2 },
  ],
  revenue: [
    { mes: "Abr", paga: 0, vencida: 0 },
    { mes: "Mai", paga: 1200, vencida: 0 },
    { mes: "Jun", paga: 297, vencida: 0 },
  ],
  losses: [
    { motivo: "Não respondeu", total: 2 },
    { motivo: "Preço", total: 1 },
  ],
};
